# Generated by rust2rpm 20
%bcond_without check
%global debug_package %{nil}

%global crate rpmrepo_metadata

Name:           rust-%{crate}
Version:        0.1.0
Release:        %autorelease
Summary:        Library for parsing RPM repository metadata

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            https://crates.io/crates/rpmrepo_metadata
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Library for parsing RPM repository metadata.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+pyo3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pyo3-devel %{_description}

This package contains library source intended for building other packages which
use the "pyo3" feature of the "%{crate}" crate.

%files       -n %{name}+pyo3-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+python-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+python-devel %{_description}

This package contains library source intended for building other packages which
use the "python" feature of the "%{crate}" crate.

%files       -n %{name}+python-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
